openapi: 3.0.0
info:
  title: SWAPI (Star Wars API)
  description: This OAS3 document (f.k.a. Swagger) describes the Star Wars API, and can be used to import the API into Axway Amplify.
  version: 0.3.0
servers:
  - url: https://swapi.dev/api
    description: The above resource is provided by the owner of Swapi, and is not an Axway resource.

paths:
  /people:
    get:
      summary: Returns a list of People.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
